### PR TITLE
Build conda packages for Sedona 1.4.1

### PR DESCRIPTION
**Pull request by Kontinuation**
Checklist
* [X] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [X] Reset the build number to `0` (if the version changed)
* [X] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [X] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by Kontinuation** [comment]
@conda-forge-admin, please rerender

**Comment by jiayuasu** [comment]
@mxr-conda @conda-forge-admin Dear all, any update on this?

**Comment by jmoraispk** [comment]
@mxr-conda, could you update us on this, please?

**Comment by jiayuasu** [comment]
@dsangillo could you please help us?

**Comment by jmoraispk** [comment]
@dherls-pltr, do you happen to have permission to merge? 

It would be great if you could help us get this new version in.

**Comment by dherls-pltr** [comment]
@jmoraispk sorry, no merge permissions here.

**Comment by jmoraispk** [comment]
Thanks, @dherls-pltr. Do you perhaps know someone that can help us here?

**Comment by jiayuasu** [comment]
Hi all, since the Apache Sedona has no control over this package, and the maintainers do not respond to our request, I suggest all Sedona users should use pip to download our Python release from Pypi: https://pypi.org/project/apache-sedona/#history

**Comment by jiayuasu** [comment]
@conda-forge-admin, please ping conda-forge/core

We have been waiting for this PR being merged for very long time. Can you add me (PMC chair of Apache Sedona) as the maintainer of this repo? So we can merge this PR ourselves?

**Comment by h-vetinari** [comment]
Sorry no-one responded earlier. It seems the shared @mxr-conda account is completely defunct, and so the only way to attract attention is by pinging the core team (which you only did now; before you were unfortunately pinging a bot account...)

Thanks for the interest in maintaining the package also on conda-forge! If you need some help with things in our infrastructure, you can ping me.

To wrap both those things up (show you which bot you were talking to, and how some of the infrastructure automation works), let's "rerender" the feedstock (bring it up to date in terms of everything that's not the package itself), and then let the bot merge if CI is still green.

@conda-forge-admin, please rerender

**Comment by h-vetinari** [comment]
> Can you add me (PMC chair of Apache Sedona) as the maintainer of this repo? So we can merge this PR ourselves?

Ah, I thought that had already happened in this PR. I'll fix it up

**Pull request merged**
